### ISSUE TITLE
Load the images with the caption

### ISSUE THREAD

**Issue by aarbelle** [igorbrigadir/DownloadConceptualCaptions#10]
Hi, 
After I downloaded the data using your code, how can I load the images with the corresponding captions?
Do you have an example of a data loader (for pytorch) or even just some python code which can load the image-caption pairs?
Thanks

**Comment by igorbrigadir** [comment]
The end result should have generated a results dataframe that should match up with the original file by row id, or you can use the name function to look up the file name in the original CSV too, the file names are based on the original URLs and row id:

https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L47-L48

I don't have any pytorch code unfortunately. If you end up writing some it would be great to share here too!

**Comment by aarbelle** [comment]
Thanks!
