### ISSUE TITLE
why the downloading is stucked in df_multiprocess?

### ISSUE THREAD

**Issue by ewrfcas** [igorbrigadir/DownloadConceptualCaptions#11]
![image](https://user-images.githubusercontent.com/12042259/131836287-30e29dab-3a7e-4fae-b9a5-e4847477c384.png)
The downloading is stucked here

**Comment by ewrfcas** [comment]
It updates, but is so slow..
![image](https://user-images.githubusercontent.com/12042259/131838422-861a0eb3-3917-478e-96da-8dba303dbd70.png)

**Comment by igorbrigadir** [comment]
Yeah you can mess with the settings a bit - specifying fewer or more images per "chunk" or how many processes here: 

https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L123-L126

**Comment by ewrfcas** [comment]
thanks for the reply! should I use fewer or larger 'images_per_part'?

**Comment by igorbrigadir** [comment]
Both - but it's hard to say, because i don't know if it's CPU or network that's the bottleneck - sometimes reducing the processes makes it go faster - do let me know how you get on, maybe it will help someone else too

**Comment by ewrfcas** [comment]
Thanks, I have rewrite a new parallel code based on yours. It can work will.

**Comment by Neo-Zhangjiajie** [comment]
@ewrfcas, I have the same problem with you, so what did you modify? images_per_part or num_process? Thanks!
