### ISSUE TITLE
conceptual-12m dataset

### ISSUE THREAD

**Issue by aniketde** [igorbrigadir/DownloadConceptualCaptions#12]
Hi,
Thanks for the scripts to download images. Are you planning to integrate https://github.com/google-research-datasets/conceptual-12m in your code in future?

**Comment by igorbrigadir** [comment]
No, I haven't thought of it but the script should work with some minimal changes:

The file name is hard coded here:  https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L136 will need to be `df = open_tsv("cc12m.tsv",data_name)`

And the 12m dataset has `url \t caption` as opposed to `caption \t url` so this needs a `names=["url","caption"]` change: https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L111

I think that's all it needs. It would be nice to have this as an option in a command line tool or something - I'm always open to PRs, but i currently don't have the bandwidth to implement this.

**Comment by aniketde** [comment]
Hi, Thanks. I was able to download it with some changes. I am doing some quality checks. I will file the PR in a few days.
