### ISSUE TITLE
Only get some intermediate files, no images, no training/validation folder

### ISSUE THREAD

**Issue by viyjy** [igorbrigadir/DownloadConceptualCaptions#13]
<img width="1342" alt="Screen Shot 2021-09-28 at 9 58 52 AM" src="https://user-images.githubusercontent.com/20442927/135132248-ed77e2e7-0b9d-40ae-99ef-5710c7698720.png">

**Comment by igorbrigadir** [comment]
what exact commands did you run? is the folder definitely not there after you clone the repo?

**Comment by viyjy** [comment]
`python download_data.py`
Right, no training/validation folder.
It takes about one day and there is no error/warning.

**Comment by igorbrigadir** [comment]
what happens when you go 

```
cd validation
```

or 

```
cd training
```

when inside that folder?

Does it work if you manually create the folders yourself with `mkdir validation` for example?

**Comment by viyjy** [comment]
no such file or directory.
BTW, I did't see any function in the `download_data.py` that creates training/validation folder and save images into these folders.

**Comment by viyjy** [comment]
![image](https://user-images.githubusercontent.com/20442927/135149556-351d2da8-4155-4b44-b518-4f79c53bf3a6.png)

This is all the information I get after running `python download_data.py` yesterday.

**Comment by igorbrigadir** [comment]
Well i'm stumped... 

this is the code that defines the file name:

https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L47-L48

and this is the code that saves the file https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L96-L99

The code assumes the folders exist already - which should be the case, they are here: https://github.com/igorbrigadir/DownloadConceptualCaptions/tree/master/training and https://github.com/igorbrigadir/DownloadConceptualCaptions/tree/master/validation

I can't reproduce this at all. What environment are you running this in? I see Ubuntu in the screenshot but what exact command did you use to clone / download the repo and what terminal are you running?

Are you sure it's definitely cloned from `master`? For example - is https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/download_data.py#L130 the same? `func=download_image` and not `func=check_download`

**Comment by viyjy** [comment]
I only clone the `download_data.py` and two `.tsv` files.
I guess I should manually create training and validation folders. 
Thanks for your help.

**Comment by igorbrigadir** [comment]
Ah ok, that explains. It would be better to clone the whole repo, and also run:

```
pip install -r requirements.txt
```

To make sure you have the dependencies

**Comment by viyjy** [comment]
Thanks.

**Comment by twangnh** [comment]
in addition, should run download_data.py within the project folder, otherwise the same problem will happen
