### ISSUE TITLE
Why I only get 80w samples?

### ISSUE THREAD

**Issue by Jxu-Thu** [igorbrigadir/DownloadConceptualCaptions#9]
in the downloaded_training_report.tsv.gz file, there are only 80w rows. Are there any problems?

**Comment by igorbrigadir** [comment]
A lot of images can disappear and be deleted, but you should be getting around 2,000,000 - i would check for any errors in the report (see the notebook https://github.com/igorbrigadir/DownloadConceptualCaptions/blob/master/downloaded_report.ipynb for an example)
